Add lvusd
curvefi/curve-assets pull request #130
Opened 2023-02-07 01:06 UTC by jasonstockman

##### Make sure file is PNG 200x200 pixels with the file name LOWER CASED

##### Team you are making the PR for:
**ArchimedesFi**
##### Link where we may find the added token on an official website/twitter to verify it's official
[https://docs.archimedesfi.com/archimedes-finance-whitepaper-(v2)#0d5b93c7b9844a5090c31c1cf190a4ae](https://docs.archimedesfi.com/archimedes-finance-whitepaper-(v2)#0d5b93c7b9844a5090c31c1cf190a4ae)

2023-02-07 11:51 UTC, philippe-git requested changes
Hey, the image resolution needs to be 200x200 please

2023-02-07 18:11 UTC, jasonstockman commented
@philippe-git Sorry about that - I noticed some recent merged PRs had higher resolution logos. I've resized ours to 200px

2023-02-09 20:16 UTC, jasonstockman commented
@philippe-git Can you take a second look please?

2023-02-09 21:23 UTC, philippe-git approved these changes

2023-02-09 21:23 UTC, merged