Add-XSTUSD-logo
curvefi/curve-assets pull request #149
Opened 2023-03-22 14:20 UTC by WRRicht3r

##### Make sure file is PNG 200x200 pixels with the file name LOWER CASED

##### Team you are making the PR for: SORA

##### Link where we may find the added token on an official website/twitter to verify it's official
sora.org

2023-03-23 21:05 UTC, philippe-git requested changes
Ah there's a space before the token address in the filename, can you please remove it so that the icon can work as expected?

2023-03-24 07:35 UTC, WRRicht3r commented
![0xc7d9c108d4e1dd1484d3e2568d7f74bfd763d356](https://user-images.githubusercontent.com/88400283/227454849-8061f99c-5e2f-4a66-9306-8235f88200f0.png)

2023-03-24 07:40 UTC, WRRicht3r commented
Sure thing!

2023-03-24 13:24 UTC, philippe-git approved these changes

2023-03-24 13:24 UTC, merged