Elixir deUSD logo
curvefi/curve-assets pull request #503
Opened 2024-07-26 22:02 UTC by shaunkh

2024-07-27 14:23 UTC, philippe-git requested changes
Thanks for the submission! Could you please make this image 200x200 before it can be merged?

2024-07-28 01:05 UTC, mimaklas approved these changes

2024-07-28 11:45 UTC, mimaklas approved these changes

2024-07-29 14:19 UTC, OnlyJousting approved these changes

2024-07-29 14:19 UTC, merged